In [1]:
import numpy as np
np.random.seed(0) # начальное значение для целей воспроизводимости

x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив
print(x1)
print("------")
print(x2)
print("------")
print(x3)

[5 0 3 3 7 9]
------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
------
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [2]:
print("x3 ndim: ", x3.ndim) # размерность
print("x3 shape: ", x3.shape) # размер каждого измерения
print("x3 size: ", x3.size) # общий размер массива
print("x3 dtype: ", x3.dtype) # общий размер массива

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int32


In [3]:
print("x3 itemsize (bytes): ", x3.itemsize, "bytes")
print("x3 nbytes: ", x3.nbytes, "nbytes")
# В общем значение атрибута nbytes должно быть равно
# значению атрибута itemsize, умноженному на size.

x3 itemsize (bytes):  4 bytes
x3 nbytes:  240 nbytes


In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x1[0]

5

In [6]:
x1[4]

7

In [7]:
x1[-1]

9

In [8]:
x1[-2]

7

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x2[0, 0]

3

In [11]:
x2[2, 0]

1

In [12]:
x2[2, -1]

7

In [13]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [14]:
x2[1,3] = 1.4
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  1],
       [ 1,  6,  7,  7]])

In [15]:
x2[1,2] = 1.6
x2
# берется пол, вне зависимости от значения запятой

array([[12,  5,  2,  4],
       [ 7,  6,  1,  1],
       [ 1,  6,  7,  7]])

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[5:]

array([5, 6, 7, 8, 9])

In [18]:
x[4:7]

array([4, 5, 6])

In [19]:
x[::2]

array([0, 2, 4, 6, 8])

In [20]:
x[1::2]

array([1, 3, 5, 7, 9])

In [21]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
x[5::-2]

array([5, 3, 1])

In [23]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  1,  1],
       [ 1,  6,  7,  7]])

In [24]:
x2[:2, :3] # две строки, три столбца

array([[12,  5,  2],
       [ 7,  6,  1]])

In [25]:
x2[:3, ::2] # все строки, каждый второй столбец

array([[12,  2],
       [ 7,  1],
       [ 1,  7]])

In [26]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 1,  1,  6,  7],
       [ 4,  2,  5, 12]])

In [27]:
print(x2[:, 0]) # первый столбец массива x2

[12  7  1]


In [28]:
print(x2[0, :]) # первая строка массива x2

[12  5  2  4]


In [29]:
print(x2[0])

[12  5  2  4]


In [30]:
print(x2)

[[12  5  2  4]
 [ 7  6  1  1]
 [ 1  6  7  7]]


In [31]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [32]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [33]:
print(x2)

[[99  5  2  4]
 [ 7  6  1  1]
 [ 1  6  7  7]]


In [34]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [35]:
x2_sub_copy[0, 0] = 109
print(x2_sub_copy)

[[109   5]
 [  7   6]]


In [36]:
print(x2)

[[99  5  2  4]
 [ 7  6  1  1]
 [ 1  6  7  7]]


In [37]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
x = np.array([1, 2, 3])

# Преобразование в вектор-строку с помощью reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [39]:
# Преобразование в вектор-строку посредством newaxis
x[np.newaxis, :]


array([[1, 2, 3]])

In [40]:
# Преобразование в вектор-столбец с помощью reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [41]:
# Преобразование в вектор-строку посредством newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [42]:

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [44]:
z = np.array([99, 99, 999, 90])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1,  99,  99, 999,  90])

In [46]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [47]:
# Слияние первой оси координат
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
# слияние по второй оси координат (с индексом 0)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [53]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

# Объединяет массивы по вертикали
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [57]:
y = np.array([[99], [99]])

# Объединяет массивы по горизонтали
np.hstack([y, grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [65]:
# разбиение массивов
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [2, 6])
print(x1, x2, x3)

[1 2] [ 3 99 99  3] [2 1]


In [68]:
grid = np.arange(1, 17).reshape((4, 4))
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
upper, lower, middle = np.vsplit(grid, [1, 2])
print(upper)
print()
print(lower)
print()
print(middle)

[[1 2 3 4]]

[[5 6 7 8]]

[[ 9 10 11 12]
 [13 14 15 16]]


In [80]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
