In [17]:
l = list(range(11))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
type(l[0])

int

In [19]:
l2 = [str(c) for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [20]:
type(l2[0])

str

In [21]:
l3 = [True, "2", 3.0, 4]
[type(item) for item in l3]

[bool, str, float, int]

In [22]:
import array
l4 = list(range(10))
A = array.array('i', l4)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
import numpy as np
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [26]:
np.array([3.14, 2, 34, 5])

array([ 3.14,  2.  , 34.  ,  5.  ])

In [27]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [28]:
# Вложенные списки преобразуются в многомерный массив
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [29]:
# Создаем массив целых чисел длины 10, заполненный нулями
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
# Создаем массив размером 3 x 5 значений с плавающей точкой,
# заполненный единицами
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
# Создаем массив размером 3 x 5, заполненный значением 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [32]:
# Создаем массив, заполненный линейной последовательностью,
# начинающейся с 0 и заканчивающейся 20, с шагом 2
# (аналогично встроенной функции range())
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
# Создаем массив из пяти значений,
# равномерно располагающихся между 0 и 1
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
# Создаем массив размером 3 x 3 равномерно распределенных
# случайных значения от 0 до 1
np.random.random((3, 3))


array([[0.18405718, 0.2773355 , 0.11503621],
       [0.3005623 , 0.58516966, 0.33303797],
       [0.31679929, 0.99777318, 0.03676485]])

In [36]:
# Создаем массив размером 3 x 3 нормально распределенных
# случайных значения с медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (3, 3))

array([[-0.92210892, -1.56664544,  0.98626883],
       [ 1.29942513,  0.69927876, -0.77137551],
       [ 0.59247596, -0.65459669,  1.08335753]])

In [37]:
# Создаем массив размером 3 x 3 случайных целых числа
# в промежутке [0, 10)
np.random.randint(0, 10, (3, 3))

array([[8, 5, 0],
       [7, 5, 1],
       [8, 9, 7]])

In [38]:
# Создаем единичную матрицу размером 3 x 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# Создаем неинициализированный массив из трех целочисленных
# значений. Значениями будут произвольные, случайно оказавшиеся
# в соответствующих ячейках памяти данные
np.empty(3)


array([1., 1., 1.])